// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwBirxE-XkY4GPCmJq0dZCdS1tOon-s60',
    appId: '1:208285833598:web:e0cf87a856defe1f3bbb2f',
    messagingSenderId: '208285833598',
    projectId: 'nemesis-hack',
    authDomain: 'nemesis-hack.firebaseapp.com',
    storageBucket: 'nemesis-hack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_D4Tu-abFkfIYVBY3e0GQpMoIQg9Bts',
    appId: '1:208285833598:android:d9cfa3ae1057d6cd3bbb2f',
    messagingSenderId: '208285833598',
    projectId: 'nemesis-hack',
    storageBucket: 'nemesis-hack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsCq5EHJNxNU60XWWCyCqvxsjVkMvSPhE',
    appId: '1:208285833598:ios:106289817b658dc13bbb2f',
    messagingSenderId: '208285833598',
    projectId: 'nemesis-hack',
    storageBucket: 'nemesis-hack.appspot.com',
    iosClientId: '208285833598-0lajto8qnm8jsk8ha962dqaureqonj3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.nemesisHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsCq5EHJNxNU60XWWCyCqvxsjVkMvSPhE',
    appId: '1:208285833598:ios:106289817b658dc13bbb2f',
    messagingSenderId: '208285833598',
    projectId: 'nemesis-hack',
    storageBucket: 'nemesis-hack.appspot.com',
    iosClientId: '208285833598-0lajto8qnm8jsk8ha962dqaureqonj3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.nemesisHackathon',
  );
}
